version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/cosmos/gaia

    steps:
      - checkout
      - run: make get_vendor_deps

      - run:
          name: Run unit tests
          command: make test
deployment:
  tag:
    tag: /v[0-9]+(\.[0-9]+)*(-.*)*/
    owner: user
    commands:
      - curl -sL https://git.io/goreleaser | bash
